### PR TITLE
Fix invalid prop: type check failed for prop "value"

### LINKED ISSUE #32: Fix vue warning when clicking `show details` of credential in Credentials page in Veres Wallet
``` 
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "undefined", got Undefined 
found in

---> <CredentialCardField> at node_modules/bedrock-vue-credential-card/CredentialCardField.vue
       <QList>
         <QCardActions>
           <QCard>
             <CredentialCardDetail> at node_modules/bedrock-vue-credential-card/CredentialCardDetail.vue
               <QCard>
                 <QPortal>
                   <QDialog>
                     <CredentialsList> at components/CredentialsList.vue
                       <QCardSection>
                         <QCard>
                           <BrQTitleCard> at node_modules/bedrock-quasar-components/BrQTitleCard.vue
                             <QPage>
                               <CredentialsPage> at components/CredentialsPage.vue
                                 <HomePage> at components/HomePage.vue
                                   <QPageContainer>
                                     <QLayout>
                                       <BrRoot> at components/BrRoot.vue
                                         <Root>
```

### PR DESCRIPTION
**Pull request by JSAssassin**
Closes #32

### CODE REVIEW

File: credentialMixin.js [hunk 1]
```diff
@@ -58,7 +58,9 @@ export const credentialMixin = {
       const fields = {};
       // order fields based on schema
       Object.keys(this.schema).map(k => {
-        fields[k] = tmpFields[k];
+        if(tmpFields[k]) {
+          fields[k] = tmpFields[k] || '';
```
Comment (aljones15) [inline credentialMixin.js]:
```suggestion
          // this is the value that will be displayed by the vue component
          fields[k] = tmpFields[k] || '';
```

**Review by aljones15 — CHANGES_REQUESTED** [review]
I love the work here, but can we get tests for how this code handles falsey values?

What happens if a credential has a value that javascript coerces to `false`

So add a credential with something like this:

```js
{
  name: '',
  phone: NaN,
  balance: 0,
  email: null,
  isDog: false
}
```

You might need to add `balance` & `isDog` to the schema in `/tests`

https://www.sitepoint.com/javascript-truthy-falsy/

p.s. also I got lint errors, but that can be handled in another PR.

File: test/web/10-CredentialCard.js [hunk 2]
```diff
@@ -11,19 +11,55 @@ function renderCredentialCard(propsData) {
...
     should.exist(vm.$el);
-    // TODO: $vm.el.something
+    vm.$el.querySelector(
+      '.q-item__section.g-field-data-regular.q-item__section--main')
+      .textContent.trim().should.equal('Mexico');
+  });
+
+  it('should not render content if type of value is falsy in credential' +
+    'subject', async () => {
+    const valueTypes = ['', NaN, 0, null, false, undefined];
```
Comment (aljones15) [inline test/web/10-CredentialCard.js]: I do think we want to show `0` and wow thanks for fixing these tests!

@gannan08 do we want to show `0` or not?

File: test/web/10-CredentialCard.js [hunk 3]
```diff
@@ -11,19 +11,55 @@ function renderCredentialCard(propsData) {
...
+        },
+        schema: {
+          birthCountry: {
+            name: 'Birth Country'
+          }
+        }
+      });
+      should.exist(vm);
+      should.exist(vm.$el);
+      should.not.exist(vm.$el.querySelector(
```
Comment (aljones15) [inline test/web/10-CredentialCard.js]: shouldn't the key name be there and the value is `''`? Where is the test for that?

File: test/web/10-CredentialCard.js [hunk 4]
```diff
@@ -11,19 +11,55 @@ function renderCredentialCard(propsData) {
...
+          credentialSubject: {
+            birthCountry: value,
+          },
+          type: ['TestCredential'],
+          description: 'Test description',
+          image: 'http://example.com/some-image.png'
+        },
+        schema: {
+          birthCountry: {
+            name: 'Birth Country'
```
Comment (aljones15) [inline test/web/10-CredentialCard.js]: this actually is an object with a name and an icon such as:

https://github.com/digitalbazaar/bedrock-vue-credential-card/blob/c86cc0b21b8ecae6ae9d6d146520d01db33c032e/test/components/Home.vue#L123-L141

I really hate to say this, but I'm not sure if the icon is optional or not.

EDIT: I think it is working with out an icon so that's fine.

**Review by aljones15 — COMMENTED** [review]
I'm really sorry about this. I wrote this almost 2 years ago now and it's poorly documented and extremely badly written. Thanks for fixing the tests. We really just need to resolve the question about if we show `0` or not. Thanks for the work.

File: credentialMixin.js [hunk 5]
```diff
@@ -58,7 +58,10 @@ export const credentialMixin = {
       const fields = {};
       // order fields based on schema
       Object.keys(this.schema).map(k => {
-        fields[k] = tmpFields[k];
+        if(tmpFields[k]) {
```
Comment (gannan08) [inline credentialMixin.js]: This check is too broad and will cause values such as `0` to not display. Can this be constricted to only check for `null` or `undefined`. It is debatable whether or not we would want to prevent displaying the empty string.

File: test/web/10-CredentialCard.js [hunk 6]
```diff
@@ -11,19 +11,55 @@ function renderCredentialCard(propsData) {
...
+        birthCountry: {
+          name: 'Birth Country'
+        }
+      }
     });
     should.exist(vm);
     should.exist(vm.$el);
-    // TODO: $vm.el.something
+    vm.$el.querySelector(
+      '.q-item__section.g-field-data-regular.q-item__section--main')
```
Comment (gannan08) [inline test/web/10-CredentialCard.js]: This query is dangerous because it depends on Quasar's internal API. These internals can be changed at any time. We need to either pin to a specific version of Quasar for these tests or even better... find another way that doesn't depend on these classes.

File: test/web/10-CredentialCard.js (hunk 2 above)
Comment (gannan08) [reply test/web/10-CredentialCard.js]: We want to display `0`.

File: test/web/10-CredentialCard.js [hunk 7]
```diff
@@ -11,19 +11,55 @@ function renderCredentialCard(propsData) {
...
+        schema: {
+          birthCountry: {
+            name: 'Birth Country'
+          }
+        }
+      });
+      should.exist(vm);
+      should.exist(vm.$el);
+      should.not.exist(vm.$el.querySelector(
+        '.q-item__section.g-field-data-regular.q-item__section--main')
```
Comment (gannan08) [inline test/web/10-CredentialCard.js]: See previous comment.

File: test/web/10-CredentialCard.js (hunk 2 above)
Comment (JSAssassin) [reply test/web/10-CredentialCard.js]: Updated.

File: test/web/10-CredentialCard.js (hunk 3 above)
Comment (JSAssassin) [reply test/web/10-CredentialCard.js]: hmm I couldn't figure out a way to get the key name, how can I get that?

File: test/web/10-CredentialCard.js (hunk 6 above)
Comment (JSAssassin) [reply test/web/10-CredentialCard.js]: hmm, I updated to use only the class `.g-field-data-regular` since it's a class that we set to the value field.

File: credentialMixin.js (hunk 5 above)
Comment (JSAssassin) [reply credentialMixin.js]: @gannan08 I have updated it to only check for null & undefined. I just wanted to point out that the value type is set to string here https://github.com/digitalbazaar/bedrock-vue-credential-card/blob/master/CredentialCardField.vue#L139, so everything we pass had to be converted to string. However doing that doesn't work for the address value since it's an object and so we will still have a vue warning when we pass an object. Let me know if you've got any suggestions on how I can solve that issue.

Comment (aljones15) [reply credentialMixin.js]: prop types can have multiple types: https://vuejs.org/v2/guide/components-props.html

so use: [String, Object] as the type and thanks for finding that.

File: test/web/10-CredentialCard.js (hunk 6 above)
Comment (gannan08) [reply test/web/10-CredentialCard.js]: @JSAssassin Great. Thank you for working on this.

**Review by gannan08 — APPROVED** [review]

**Review by aljones15 — APPROVED** [review]
I'm approving this as this expands test coverage and also corrects several mistakes in the code.

Do look out for stuff this like though:

```js
     // eslint-disable-next-line no-unused-vars
```

if we're not using a var it might be safe to delete it.
